### ISSUE TITLE
Sound Settings fail to compile

### ISSUE THREAD

**Issue by utak3r** [AOKP/packages_apps_Settings#13]
SoundsSystem.java fails to compile after commit:
d4ef0bbab4aa73485e73ca742da61a51894b1184

claiming it cannot find symbol Settings.System.VOLUME_ADJUST_SOUNDS_ENABLED.

**Comment by kecinzer** [comment]
It depends on framework/base part.

**Comment by utak3r** [comment]
Ok, I see it. Thanks.

**Comment by JunioStk** [comment]
Gosto muito da aokp, más o som da chamada não funciona, podem resolver isso ?
